# Generated by Django 3.1.5 on 2021-02-18 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=8)),
                ('lastName', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dept', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(default='', max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, default='0', null=True, upload_to='')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=30, null=True)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('usertype', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('loginTime', models.DateTimeField()),
                ('logoutTime', models.DateTimeField(null=True)),
                ('sessionId', models.IntegerField(default='')),
                ('agentId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('requestedUserName', models.CharField(max_length=30, null=True)),
                ('requestedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('approvedBy', models.CharField(default='', max_length=30, null=True)),
                ('approvedDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('requestType', models.CharField(max_length=20, null=True)),
                ('requestedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=30, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Dno', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Pincode', models.CharField(max_length=6)),
                ('AddressType', models.CharField(choices=[('PermanentAddress', 'PermanentAddress'), ('TemporaryAddress', 'TemporaryAddress')], max_length=30)),
                ('Agent', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
    ]
