# Generated by Django 3.1.5 on 2021-03-02 05:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('BranchName', models.CharField(default='', max_length=40)),
                ('BranchCode', models.CharField(default='', max_length=40)),
                ('GSTid', models.CharField(default='', max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
        migrations.CreateModel(
            name='MyAddressTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Dno', models.CharField(default='', max_length=10)),
                ('Street', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=20)),
                ('State', models.CharField(default='', max_length=20)),
                ('Country', models.CharField(default='', max_length=20)),
                ('Pincode', models.CharField(default='', max_length=6)),
                ('AddressType', models.CharField(choices=[('PermanentAddress', 'PermanentAddress'), ('TemporaryAddress', 'TemporaryAddress')], max_length=30)),
                ('agent_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
                ('branch_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.branch')),
            ],
            options={
                'ordering': ['Dno', 'Street', 'City', 'State', 'Country', 'Pincode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('code', models.CharField(default='', max_length=40)),
                ('GSTCode', models.CharField(default='', max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
        migrations.DeleteModel(
            name='AddressTable',
        ),
        migrations.AddField(
            model_name='myaddresstable',
            name='partner_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.partner'),
        ),
    ]
