# Generated by Django 3.1.5 on 2021-01-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttable',
            name='usertype',
            field=models.CharField(default='', max_length=30),
        ),
    ]
