# Generated by Django 3.1.5 on 2021-02-26 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20210226_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('code', models.CharField(default='', max_length=40)),
                ('GSTCode', models.CharField(default='', max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
    ]
