# Generated by Django 3.1.5 on 2021-02-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20210131_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttable',
            name='confirmPassword',
        ),
    ]
