# Generated by Django 3.1.5 on 2021-02-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_remove_agenttable_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('loginTime', models.DateTimeField()),
                ('logoutTime', models.DateTimeField()),
                ('sessionId', models.IntegerField(default='')),
            ],
        ),
    ]
