# Generated by Django 3.1.5 on 2021-03-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20210309_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Sno', models.CharField(default='', max_length=40)),
                ('Description', models.CharField(default='', max_length=40)),
                ('HSNCode', models.CharField(default='', max_length=40, null=True)),
                ('UOM', models.CharField(default='', max_length=40, null=True)),
                ('QtyPerKg', models.CharField(default='', max_length=40)),
                ('RatePerKg', models.CharField(default='', max_length=40)),
                ('TotalQtyCost', models.CharField(default='', max_length=40)),
                ('TransportCharges', models.CharField(default='', max_length=40, null=True)),
                ('IGST', models.CharField(default='', max_length=40, null=True)),
                ('CGST', models.CharField(default='', max_length=40, null=True)),
                ('TotalTax', models.CharField(default='', max_length=40, null=True)),
                ('partner', models.CharField(default='', max_length=40)),
                ('branch', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
