# Generated by Django 3.1.5 on 2021-02-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_logtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='logoutTime',
            field=models.DateTimeField(null=True),
        ),
    ]
