# Generated by Django 3.1.5 on 2021-02-26 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_myaddresstable_partner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('BranchName', models.CharField(default='', max_length=40)),
                ('BranchCode', models.CharField(default='', max_length=40)),
                ('GSTid', models.CharField(default='', max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
    ]
