# Generated by Django 3.1.5 on 2021-02-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaddresstable',
            name='branch_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.branch'),
        ),
    ]
