# Generated by Django 3.1.5 on 2021-02-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_auto_20210207_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='agentId',
            field=models.IntegerField(default=0),
        ),
    ]
