# Generated by Django 3.1.5 on 2021-02-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_logtable_agentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Dno', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Pincode', models.CharField(max_length=6)),
                ('AddressType', models.CharField(choices=[('PermanentAddress', 'PermanentAddress'), ('TemporaryAddress', 'TemporaryAddress')], max_length=30)),
                ('Agent', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
    ]
