# Generated by Django 3.1.5 on 2021-02-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_logtable_agentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('dno', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('address_type', models.CharField(choices=[('p', 'permanent address'), ('t', 'temporary address')], max_length=1)),
                ('agent', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
    ]
