# Generated by Django 3.1.5 on 2021-02-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pDno', models.CharField(max_length=10)),
                ('pStreet', models.CharField(max_length=20)),
                ('pCity', models.CharField(max_length=20)),
                ('pState', models.CharField(max_length=20)),
                ('pPincode', models.CharField(max_length=6)),
                ('pAddressType', models.CharField(choices=[('PA', 'Permanent Address'), ('TA', 'TemporaryAddress')], max_length=2)),
                ('pAgent', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tDno', models.CharField(max_length=10)),
                ('tStreet', models.CharField(max_length=20)),
                ('tCity', models.CharField(max_length=20)),
                ('tState', models.CharField(max_length=20)),
                ('tPincode', models.CharField(max_length=6)),
                ('tAddressType', models.CharField(choices=[('PA', 'Permanent Address'), ('TA', 'TemporaryAddress')], max_length=2)),
                ('tAgent', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agent.agenttable')),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
